{
    'name': 'AMPATH Medical Terminology',
    'version': '17.0.1.0.1',
    'summary': 'Replaces generic business terms with medical terminology',
    'author': 'AMPATH Kenya',
    'category': 'Customizations',
    'depends': [
        'base',
        'sale_management',
        'account',
        'stock',
        'purchase',
        'mrp',
        'product',
        'ampath_billing',
    ],
    'data': [
        'views/sale_views.xml',
        'views/stock_views.xml',
        'views/account_views.xml',
        'views/product_views.xml',
        'views/purchase_views.xml',
        'views/mrp_views.xml',
        'views/res_partner_views.xml',
        'views/menu_overrides.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
