name: Build and Publish Docker Images

on:
  push:
    branches: [main]
    tags: ['v*']
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    
    strategy:
      matrix:
        image:
          - name: backend
            dockerfile: ./Dockerfile
            context: .
          - name: frontend
            dockerfile: ./frontend/Dockerfile
            context: ./frontend
          - name: gateway
            dockerfile: ./gateway/Dockerfile
            context: ./gateway

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        if: matrix.image.name == 'backend'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Create clean Maven settings
        if: matrix.image.name == 'backend'
        run: |
          # Remove any existing settings file to start fresh
          rm -rf ~/.m2/settings.xml
          mkdir -p ~/.m2
          
          # Create a clean settings file with only our GitHub server
          cat > ~/.m2/settings.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                        http://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>github</id>
                <username>GITHUB_ACTOR_PLACEHOLDER</username>
                <password>GITHUB_TOKEN_PLACEHOLDER</password>
              </server>
            </servers>
          </settings>
          EOF
          
          # Replace placeholders with actual values
          sed -i "s/GITHUB_ACTOR_PLACEHOLDER/${{ github.actor }}/g" ~/.m2/settings.xml
          sed -i "s/GITHUB_TOKEN_PLACEHOLDER/${{ secrets.GITHUB_TOKEN }}/g" ~/.m2/settings.xml

      - name: Copy Maven settings for Docker
        if: matrix.image.name == 'backend'
        run: |
          mkdir -p ${{ github.workspace }}/.m2
          cp ~/.m2/settings.xml ${{ github.workspace }}/.m2/settings.xml
          echo "=== Maven settings file content ==="
          cat ${{ github.workspace }}/.m2/settings.xml
          echo "=== End of settings file ==="

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Debug Maven settings before Docker build
        if: matrix.image.name == 'backend'
        run: |
          echo "=== Checking settings file before Docker build ==="
          echo "Settings file path: ${{ github.workspace }}/.m2/settings.xml"
          if [ -f "${{ github.workspace }}/.m2/settings.xml" ]; then
            echo "✅ Settings file exists"
            echo "File size: $(stat -c%s ${{ github.workspace }}/.m2/settings.xml) bytes"
            echo "File permissions: $(ls -la ${{ github.workspace }}/.m2/settings.xml)"
            echo ""
            echo "=== Settings file content ==="
            cat ${{ github.workspace }}/.m2/settings.xml
            echo ""
            echo "=== End of settings file ==="
            echo ""
            echo "=== First 50 characters (with escape sequences) ==="
            head -c 50 ${{ github.workspace }}/.m2/settings.xml | od -c
            echo ""
            echo "=== XML validation ==="
            if command -v xmllint &> /dev/null; then
              xmllint --noout ${{ github.workspace }}/.m2/settings.xml && echo "✅ XML is valid" || echo "❌ XML is invalid"
            else
              echo "xmllint not available for validation"
            fi
          else
            echo "❌ Settings file does not exist!"
            echo "Contents of .m2 directory:"
            ls -la ${{ github.workspace }}/.m2/ || echo "No .m2 directory found"
          fi
          echo "=== End debug info ==="

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            m2settings=${{ github.workspace }}/.m2/settings.xml
          build-args: |
            CACHE_BUST=${{ github.sha }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.image.name }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true